application:
  api:
    param:
      format: format
      id: id
      plot: plot
      title: title
      year: year
  async:
    core-pool-size: 20
    max-pool-size: 1000
    thread-name-prefix: fluffy-
    wait-for-tasks-to-complete-on-shutdown: true
  cache:
    cache-documents-max-size: 3
    cache-response-bodies-max-size: 15
  data-source:
    api:
      param:
        api-key: apikey
        format: r
        id: i
        plot: plot
        title: t
        year: y
    api-key: 225ea49b
    host: www.omdbapi.com
    json:
      key:
        actors: Actors
        awards: Awards
        box-office: BoxOffice
        country: Country
        director: Director
        genre: Genre
        imdb-id: imdbID
        imdb-rating: imdbRating
        imdb-votes: imdbVotes
        language: Language
        metascore: Metascore
        plot: Plot
        poster: Poster
        production: Production
        rated: Rated
        ratings: Ratings
        ratings.source.source: Source
        ratings.source.value: Value
        released: Released
        response: Response
        runtime: Runtime
        title: Title
        type: Type
        writer: Writer
        year: Year
      value:
        bad-response: false
        default-string-field: '-'
    plot-mode:
      full: full
      short: short
    protocol: http
    response-data-format:
      docx: ''
      json: json
      xml: xml
  document-template:
    field:
      actors: actors
      author: author
      awards: awards
      boxOffice: boxOffice
      country: country
      currentYear: currentYear
      director: director
      genre: genre
      imdbID: imdbID
      imdbRating: imdbRating
      imdbVotes: imdbVotes
      language: language
      metascore: metascore
      plot: plot
      poster: poster
      production: production
      rated: rated
      released: released
      runtime: runtime
      title: title
      type: type
      writer: writer
      year: year
    filename: Template.docx
    poster-name: Poster
    ratings-table-anchor: Metascore
  endpoint:
    film-data: /film
    film-document: /film
  exception-handling: ''
  exception-message:
    application-inner-exception: Внутрішня виключна ситуація додатка
    bad-input: Некоректні вхідні дані
    bad-poster-extension: Неправильне розширення файлу постера
    data-gathering-failed: Не вдалося отримати дані
    no-data-found: Даних за значеннями параметрів запиту не знайдено
  host: localhost:8080
  name: FilmInfo
  no-poster-image-filename: NoPoster.png
  plot-mode:
    default: ${application.plot-mode.short}}
    full: full
    short: short
  protocol: http
  response-data-format:
    default: ${application.response-data-format.json}
    docx: docx
    json: json
    xml: xml
  result-document:
    filename: AboutFilm.docx
    mime-subtype: vnd.openxmlformats-officedocument.wordprocessingml.document
    mime-type: application